version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app
    overwrite: yes

permissions:
  - object: /
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/backup_env.sh
      timeout: 60
      runas: ubuntu
  AfterInstall:
    - location: scripts/restore_env.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu
